### GET request to example server
POST http://localhost:8080/api/cao/inserir
Content-Type: application/json

{
  "nome": "Scooby-doo",
  "data_nascimento": "2026-03-17",
  "tutor_id": 39,
  "turma": "A",
  "data_cadastro": "2027-01-01",
  "sexo": "M",
  "raca": "Sem raça definida",
  "ativo": true,
  "tem_pedigree": false,
  "rga": "RGA123456",
  "sin_patinhas": "sim",
  "aceito": true,
  "imagem": "https://imagem.com",
  "alergias": "Nenhuma",
  "situacao": "SCOOBY DOBY DOOO!!!"
}

###