### GET request to example server
POST http://localhost:8080/api/cao/inserir
Content-Type: application/json

{
  "nome": "Orelha",
  "dataNascimento": "2016-07-08",
  "tutorId": 1,
  "turma": "1E",
  "dataCadastro": "2026-01-01",
  "sexo": "M",
  "raca": "Sem raça definida",
  "ativo": false,
  "temPedigree": false,
  "rga": "RGA-123456",
  "sinPatinhas": "sim",
  "aceito": true,
  "imagem": "https://imagem.com",
  "alergias": "Nenhuma"
}

###